Repository Agijagi/Agijagi-Seller, pull requests merged in 2023-11, with the labels that each got.

#2 [Feat] 네비게이션 연결 및 로그인 화면 구현
  app/build.gradle.kts
  app/src/main/java/com/likelion/agijagiseller/feature/login/LoginFragment.kt
  app/src/main/java/com/likelion/agijagiseller/global/MainActivity.kt
  app/src/main/res/drawable/arrow_back_24px.xml
  app/src/main/res/drawable/google_login.png
  app/src/main/res/drawable/thumbnail.png
  app/src/main/res/drawable/wide_box_rounded_button_stroke.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
Labels: Design, Feat

#4 Chore: .gitignore 적용 #3
  .gitignore
  local.properties
Labels: Chore

#7 Design: 회원가입 화면 구현 및 로그인화면 수정 #6
  app/src/main/java/com/likelion/agijagiseller/feature/signup/SignupFragment.kt
  app/src/main/res/drawable/small_box_rounded_button_stroke.xml
  app/src/main/res/drawable/wide_box_rounded_stroke.xml
  app/src/main/res/drawable/wide_box_selected_active.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: Design

#9 Design: 홈화면구성 UI #8
  app/src/main/java/com/likelion/agijagiseller/feature/home/HomeFragment.kt
  app/src/main/res/drawable/chat_24px.xml
  app/src/main/res/drawable/notifications_24px.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/menu/menu_home.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: Design

#12 Design: 스토어관리 UI #10
  app/src/main/java/com/likelion/agijagiseller/feature/storemanagement/StoreManagementFragment.kt
  app/src/main/res/layout/fragment_store_management.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: Design

#15 Design: 상품 상세 및 미리보기 화면 구현 #14
  app/src/main/java/com/likelion/agijagiseller/feature/product/ProductDetailFragment.kt
  app/src/main/res/drawable/product_detail_default_image.png
  app/src/main/res/drawable/wide_box_bottom_active.xml
  app/src/main/res/layout/fragment_product_detail.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: Design

#17 Design: 홈화면 주석제거 및 회원가입화면 View 제약조건 수정 #11
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_signup.xml
Labels: Design

#18 Design: 알림설정 화면 구현 #13
  app/src/main/res/color/switch_toggle_color.xml
  app/src/main/res/color/switch_toggle_track_color.xml
  app/src/main/res/layout/fragment_notification_setting.xml
Labels: Design

#19 Design: 상품 등록 및 수정 화면 UI 구현 #16
  app/src/main/res/drawable/agijagi_logo_vector_square.xml
  app/src/main/res/drawable/check_circle_24px.xml
  app/src/main/res/drawable/circle_checkbox_selector.xml
  app/src/main/res/drawable/close_24px.xml
  app/src/main/res/drawable/radio_button_unchecked_24px.xml
  app/src/main/res/layout/fragment_product_registration.xml
  app/src/main/res/layout/item_product_registration_picture.xml
  app/src/main/res/layout/item_product_registration_plan.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/array.xml
Labels: Design

#22 Design: 폰트 추가 및 툴바 폰트적용
  app/src/main/res/font/nanum_square_round_otf_b.otf
  app/src/main/res/font/nanum_square_round_otf_l.otf
  app/src/main/res/font/nanum_square_round_otf_r.otf
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_product_registration.xml
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/typography.xml
Labels: Design

#23 Design: 주문 배송 관리 화면 구현 #20
  app/build.gradle.kts
  app/src/main/res/drawable/shopping_list_no_item_logo.png
  app/src/main/res/layout/fragment_order_shipping_management.xml
  app/src/main/res/layout/item_order_management.xml
  app/src/main/res/layout/item_order_management_shimmer.xml
Labels: Design

#26 Fix: 리소스 중복 제거
  app/src/main/res/values/typography.xml
Labels: Fix

#28 Chore: git ignore 설정 변경 적용 #27
  .gitignore
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: Chore

#31 Design: 채팅메인 화면 구현 #30
  app/src/main/java/com/likelion/agijagiseller/feature/chatting/ChattingRoomFragment.kt
  app/src/main/res/drawable/delete_24px.xml
  app/src/main/res/drawable/narrow_box_rounded_button_solid.xml
  app/src/main/res/drawable/narrow_box_rounded_button_stroke.xml
  app/src/main/res/drawable/shopping_list_small_circle_checkbox_selector.xml
  app/src/main/res/layout/fragment_chatting.xml
  app/src/main/res/layout/fragment_chatting_room.xml
  app/src/main/res/layout/layout_bottom_cancel_delete_button.xml
  app/src/main/res/menu/menu_chatting.xml
Labels: Design

#33 Design: 채팅리스트 화면, 채팅 룸 화면 구현 #30
  app/src/main/res/drawable/arrow_circle_right_24px.xml
  app/src/main/res/drawable/chatting_input_box.xml
  app/src/main/res/drawable/chatting_message_box_my_chat.xml
  app/src/main/res/drawable/chatting_message_box_other_chat.xml
  app/src/main/res/drawable/check_circle_20px.xml
  app/src/main/res/drawable/image_24px.xml
  app/src/main/res/drawable/new_mark.xml
  app/src/main/res/drawable/radio_button_unchecked_20px.xml
  app/src/main/res/layout/fragment_chatting.xml
  app/src/main/res/layout/fragment_chatting_room.xml
  app/src/main/res/layout/item_chatting.xml
  app/src/main/res/layout/item_chatting_room_my_chat.xml
  app/src/main/res/layout/item_chatting_room_other_chat.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/values/typography.xml
Labels: Design
